apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: application
  name: demo-replicaset
  label:
    app: demo-replicaset

spec:
  replicas: 3
  selector:
    app: demo-replicaset
  template:
    metadata:
      name: demo-replicaset
      labels:
        app: demo-replicaset
    spec:
      containers:
        - name: demo-replicaset
          image: nginx
          ports:
            - containerPort: 80
              name: web
          env:
            - name: development
